spring:
  profiles:
    active: default
  cloud:
    stream:
      kafka:
        streams:
          binder:
            application-id: fk-example-1
            brokers: localhost:19092,localhost:29092,localhost:39092
            deserialization-exception-handler: logandcontinue
            configuration:
              commit.interval.ms: 1000
