/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package types;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class Click extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5884605695501139646L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Click\",\"namespace\":\"types\",\"fields\":[{\"name\":\"InventoryID\",\"type\":\"string\"}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Click> ENCODER =
          new BinaryMessageEncoder<Click>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Click> DECODER =
          new BinaryMessageDecoder<Click>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Click> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Click> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Click> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Click>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Click to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Click from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Click instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Click fromByteBuffer(
          java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence InventoryID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Click() {
  }

  /**
   * All-args constructor.
   *
   * @param InventoryID The new value for InventoryID
   */
  public Click(java.lang.CharSequence InventoryID) {
    this.InventoryID = InventoryID;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return InventoryID;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        InventoryID = (java.lang.CharSequence) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'InventoryID' field.
   *
   * @return The value of the 'InventoryID' field.
   */
  public java.lang.CharSequence getInventoryID() {
    return InventoryID;
  }


  /**
   * Sets the value of the 'InventoryID' field.
   *
   * @param value the value to set.
   */
  public void setInventoryID(java.lang.CharSequence value) {
    this.InventoryID = value;
  }

  /**
   * Creates a new Click RecordBuilder.
   *
   * @return A new Click RecordBuilder
   */
  public static types.Click.Builder newBuilder() {
    return new types.Click.Builder();
  }

  /**
   * Creates a new Click RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new Click RecordBuilder
   */
  public static types.Click.Builder newBuilder(types.Click.Builder other) {
    if (other == null) {
      return new types.Click.Builder();
    } else {
      return new types.Click.Builder(other);
    }
  }

  /**
   * Creates a new Click RecordBuilder by copying an existing Click instance.
   *
   * @param other The existing instance to copy.
   * @return A new Click RecordBuilder
   */
  public static types.Click.Builder newBuilder(types.Click other) {
    if (other == null) {
      return new types.Click.Builder();
    } else {
      return new types.Click.Builder(other);
    }
  }

  /**
   * RecordBuilder for Click instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Click>
          implements org.apache.avro.data.RecordBuilder<Click> {

    private java.lang.CharSequence InventoryID;

    /**
     * Creates a new Builder
     */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(types.Click.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.InventoryID)) {
        this.InventoryID = data().deepCopy(fields()[0].schema(), other.InventoryID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Click instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(types.Click other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.InventoryID)) {
        this.InventoryID = data().deepCopy(fields()[0].schema(), other.InventoryID);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Gets the value of the 'InventoryID' field.
     *
     * @return The value.
     */
    public java.lang.CharSequence getInventoryID() {
      return InventoryID;
    }


    /**
     * Sets the value of the 'InventoryID' field.
     *
     * @param value The value of 'InventoryID'.
     * @return This builder.
     */
    public types.Click.Builder setInventoryID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.InventoryID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'InventoryID' field has been set.
     *
     * @return True if the 'InventoryID' field has been set, false otherwise.
     */
    public boolean hasInventoryID() {
      return fieldSetFlags()[0];
    }


    /**
     * Clears the value of the 'InventoryID' field.
     *
     * @return This builder.
     */
    public types.Click.Builder clearInventoryID() {
      InventoryID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Click build() {
      try {
        Click record = new Click();
        record.InventoryID = fieldSetFlags()[0] ? this.InventoryID : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Click>
          WRITER$ = (org.apache.avro.io.DatumWriter<Click>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out)
          throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Click>
          READER$ = (org.apache.avro.io.DatumReader<Click>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in)
          throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override
  protected boolean hasCustomCoders() {
    return true;
  }

  @Override
  public void customEncode(org.apache.avro.io.Encoder out)
          throws java.io.IOException {
    out.writeString(this.InventoryID);

  }

  @Override
  public void customDecode(org.apache.avro.io.ResolvingDecoder in)
          throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.InventoryID = in.readString(this.InventoryID instanceof Utf8 ? (Utf8) this.InventoryID : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
          case 0:
            this.InventoryID = in.readString(this.InventoryID instanceof Utf8 ? (Utf8) this.InventoryID : null);
            break;

          default:
            throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










